# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  
  
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: test-CI-network
          template-file-path: cloudformation/lecture13-network.yml
      - aws-cloudformation/deploy:
          stack-name: test-CI-security
          template-file-path: cloudformation/lecture13-security.yml
      - aws-cloudformation/deploy:
          stack-name: test-CI-resource
          template-file-path: cloudformation/lecture13-resource.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: RDSpassword=$AWS_DB_PW

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  CircleCI-Practice-workflow:
    jobs:
      - execute-cloudformation
